baseURL = "https://sdir-h-cdnep-externalapi.azureedge.net/"
languageCode = "en"
defaultContentLanguage = "en"

contentDir = "content"
staticDir = "static"
publishDir = "public"

title = "Sdir docs"
theme = "hugo-theme-altinn"
metadataFormat = "yaml"
pluralizeListTitles = false
preservetaxonomynames = true
enableEmoji = true
enableGitInfo = false
disableKinds = ["RSS"] # page home section taxonomy taxonomyTerm RSS sitemap robotsTXT 404

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "dracula"

[markup.tableOfContents]
startLevel = 2
endLevel = 2
ordered = false

[blackfriday]
fractions = false # disable automatic fraction rendering

[params]
editURL = "https://github.com/Sjofartsdirektoratet/docs/blob/master/content/"
noHomeIcon = true # default is false
noSearch = false # default is false
disableNavChevron = false
showVisitedLinks = false # default is false
# themeVariant = "gray" # choose theme variant "gray" for systemdocumentation, like Altinnpedia. Blue theme is for altinndigitalisering.


[outputs]
home = ["HTML", "JSON"] # JSON generates index.json file used by search
